name: Delayed Publish

on:
  schedule:
    # '0 9 25 12 *' — 25 декабря в 09:00
    - cron: '0 9 25 12 *' 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge hidden-content into main
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git checkout main
          git merge origin/hidden-content
          git push origin main